### PR TITLE
Automatically convert dicts to nested HParams

### PR DESCRIPTION
**Pull request by fdraxler**

### CODE REVIEW

**Comment by fdraxler** [comment]
Please do not merge yet, I will add support for optimal HParams, i.e. nested: NestedHparams | None and nested: Optional[NestedHParams]

**Comment by fdraxler** [comment]
From my side, nested HParams work now :)

**Comment by fdraxler** [comment]
If the type is hinted as optional, then the resulting annotated type is `Union[XHParams, None]`. We need to identify which `XHParams` class is required by unpacking the Union specs. 

But what happens if more than `XHParams | None` types are allowed? When should we convert it? Right now, I opted to only convert the type when the only non-`None` type is a subclass of `HParams`. Do you think this is reasonable?

**Comment by LarsKue** [comment]
I think we should assume the user will provide reasonable type hints. The only way for the conversion to wrongfully fail is if the user provides a type hint of `foo: XHParams | dict` and wants a dictionary that is not convertible to `XHParams`.

I think a better approach would be to check if the union contains any `HParams` subclasses, and always attempt the conversion, if provided a dict. If the type hint also contains `dict`, and the conversion fails, we leave it as a dict.

**Comment by fdraxler** [comment]
Okay, how about we throw a specification error when the user specified `foo: XHParams | dict` and cast `XHParams(**value)` only if `value` is a `dict`? Or is there any reasonable application for `foo: XHParams | dict`?

**Comment by LarsKue** [comment]
I implemented the conversion `dict -> XHParams` for arbitrary unions, but opted to ignore `XHParams | dict` for now for code simplicity. The code is already a bit lengthy, I think we can still make some improvement here before merging to main.

**Pull request merged**
